== El Diario de Job Scott

Por cuanto le ha placido a la Divina Sabiduría guiar
y conducir mi alma a través de muchas,
diferentes y dolorosas dispensaciones,
así como también a través de algunos tiempos de gozo muy
consoladores--haciéndome en gran medida partícipe de aflicciones,
sosteniendo mi mente a través de ellas, produciendo en mí una y otra vez gozo,
después de escenas de profunda angustia,
y preservándome maravillosamente a través de algunas pruebas profundas
y poco comunes en mi viaje hacia la tierra de reposo--siento,
y a menudo he sentido,
un compromiso en mi mente de dejar atrás algunas notas en
memoria de Sus misericordiosos tratos conmigo desde mi juventud.

Nací, de acuerdo con el mejor registro que pude obtener, el 18 del mes Décimo de 1751,
en el municipio de Providence,
en la colonia (ahora estado) de Rhode Island en Nueva Inglaterra.
Los nombres de mis padres eran John y Lydia Scott;
quienes eran considerados personas honestas,
aunque mi padre nunca profesó ser un hombre muy religioso.
Mi madre era más celosa y asistía a las reuniones de los Amigos cuando podía,
llevándome con ella en varias ocasiones, y creo que a uno o dos más de los niños,
aunque todos éramos jóvenes; pues yo, siendo el mayor,
sólo tenía unos diez años cuando ella murió. Puedo recordar
bien las serias impresiones y reflexiones que,
en ese período temprano de vida, y por algunos años antes de la muerte de mi madre,
ocupaban mi mente mientras estaba sentado en las reuniones con ella, y de camino a casa.
Yo incluso tenía deseos de convertirme en un verdadero religioso,
y servir y temer a Dios, como lo hicieron Abraham, Isaac y Jacob,
y otros de los que había leído u oído.

Mi madre se esforzó mucho por impedir que nosotros
estuviéramos en compañía de niños rudos y corruptos,
y a veces nos llamaba y procuraba que nos sentáramos juntos en silencio con ella,
lo cual hacíamos.
Y aunque en ese momento no entendía mucho la razón por la que lo hacía,
desde entonces me ha suministrado un grado de sólida satisfacción, creer,
que el Señor le había dado a ella experimentar y participar de los sublimes deleites
y sustanciosos beneficios del verdadero silencio Cristiano en el interior,
y de esperar en Dios; y saber,
que ella deseaba (aún desde nuestra más temprana edad) que nosotros
conociéramos esos toques secretos del divino favor que ella,
sin ninguna duda, sentía y experimentaba en los tiempos de retiro.
Y aunque, como he observado antes, yo entendía poco en ese momento,
desde entonces he tenido razones para creer que esos
tiempos realmente fueron de provecho para mí,
y a menudo han sido recordados para mi beneficio.

Estoy completamente convencido de la gran ventaja y utilidad espiritual,
para los niños y otros, que resulta de esperar frecuentemente en el Señor en silencio.
He visto evidencia viva y convincentemente de esto, incluso en niños de muy poca edad;
y creo plenamente que las impresiones de la bondad divina que han
sido estampadas en la mente durante esos tiempos (es decir,
cuando no se ha pronunciado ni una palabra con la boca),
han permanecido de forma duradera,
y han tendido poderosamente a engendrar el verdadero
temor y amor a Dios en corazones jóvenes y tiernos.
Ojalá los padres, en general,
se preocuparan en hacer todo lo posible por llevar a su
tierna descendencia a un conocimiento de las cosas divinas,
y al sentido de ellas en su juventud; lo cual se aprende mejor y de manera más viva,
y se sella en el alma al experimentarlas verdaderamente en un estado de silencio
interno en el que el alma se vuelve hacia adentro y busca palpar a Dios.

Algunos de mis parientes que estuvieron presente cuando mi madre falleció,
(porque como fue de noche,
yo no estaba allí) dijeron que su partida fue alegre y gloriosa;
y que casi su último aliento lo gastó en ferviente súplica al Señor su Dios.

Y ahora, sabiendo sin duda alguna, que su espíritu inmortal descansa en Jesús,
dejo su relato y procedo contar más acerca del ejercicio de mi propia mente,
con el siguiente testimonio: hasta donde alcanza mi memoria,
recuerdo muy bien las obras secretas del Señor en
mi corazón (por Su gracia o Espíritu Santo),
trayéndome bajo un sentido de condenación por mis malos pensamientos y acciones,
por mis groserías y malas palabras, por la desobediencia hacia mis padres,
por desear el mal a los que me ofendían y por todo
tipo de actitudes y prácticas infantiles y corruptas.
De hecho, puedo decir que, más allá de toda la instrucción externa que recibí,
el Espíritu de la Verdad me hizo sentir en mi interior que estas cosas eran malas,
y que brotaban de una raíz de maldad que realmente estaba presente en mí.

Sé que algunos hombres argumentan que todo lo que
conocemos del bien y del mal es a través de la educación,
la enseñanza, o de lo que hemos percibido y recibido de otros;
y que la influencia de la costumbre y de la opinión determina y es la norma de la moral.
Pero la falacia de este argumento puede evidenciarse fácilmente,
a través del testimonio de mi propia experiencia (y no dudo que
la de miles también). Porque en los primeros años de mi vida,
llegué a ser sensible y a estar convencido de que ciertos pensamientos, deseos,
e inclinaciones de mi propia mente--de los que ningún otro mortal sabía nada,
y sobre los que nunca había tenido ninguna precaución, consejo,
o instrucción humana--eran de una tendencia corrupta y malvada,
y surgían de una fuente corrupta en mí. Y estoy plenamente convencido de que,
en cualquier parte del mundo, los niños (a una temprana edad),
tienen puesto delante de ellos el bien y el mal (mediante la luz de Cristo que alumbra
en sus corazones) con suficiente claridad y evidencia como para hacerles saber su deber,
si le prestan atención. Y aunque estoy profundamente consciente
de la necesidad y de lo provechoso de una tutela,
crianza, e instrucción cuidadosa,
a fin de proteger a los niños contra la influencia corrupta del ejemplo, incitación,
e inclinación perversa que los rodean abundante y frecuentemente;
sin embargo me temo que una gran parte de lo que se llama educación o instrucción cristiana,
tiende más bien a debilitar el verdadero sentido
y evidencia de la verdad divina en la mente,
y a sustituirlo por nociones y métodos,
que a fomentar una atención sincera a ese Espíritu que guía a toda verdad.
Estoy convencido, de que,
si las enseñanzas de los hombres nunca se opusieran a las enseñanzas del Espíritu Santo,
muchas cosas que suelen fomentarse como "`cosas inocentes y confiables`"
se verían como cosas malas en las mentes de los niños. Y,
por otro lado, creo que verían claramente, conforme vayan creciendo,
que la religión no tiene nada que ver con los rituales y
prácticas que comúnmente se consideran (por una distorsión
del verdadero discernimiento) importantes en la vida religiosa.
En verdad,
es lamentable observar cuántos niños ahora son alentados
por sus ciegos cuidadores al orgullo,
a la vanidad y a la venganza;
son enseñados a enorgullecerse en una supuesta superioridad de habilidades y logros;
criados con ideas de grandeza y honor mundano; inspirados con conceptos altivos de valor,
heroísmo y matanza humana;
y al mismo tiempo reposando sin preocupación en una serie de prácticas religiosas externas,
considerando que esto satisface las demandas de Dios.

En cuanto a mi familiaridad con la operación del
Espíritu Santo en mis primeros años de vida,
si bien entonces no sabía lo que era,
ahora estoy tan seguro de ello como lo estoy de la existencia y omnipresencia de Dios.
Tengo muy claro que, a los seis o siete años,
el principio interno (que es la mano y el poder de Dios,
que opera amorosamente en el alma), se estableció,
brilló y se movió dentro de mí de tal manera,
que me dio un sentido seguro y distinguible en varios aspectos de lo correcto e incorrecto,
o del bien y del mal;
y en algunas de estas cosas lo hizo totalmente independiente
de cualquier información humana.
Está grabado en mi corazón con mucha
claridad y certeza que este era el Espíritu del Dios viviente,
el mismo que visita, atrae, invita, y contiende con todos (al menos por un tiempo),
porque Dios no hace acepción de personas.
Y creo tan plenamente que ningún hombre puede tener un conocimiento claro de Dios,
o de su propio deber religioso, sin la influencia del Espíritu Santo,
como creo que la sabiduría de este mundo es insensatez para Dios,
y que el mundo por su sabiduría no Lo conoce.
¡Oh, qué vivo y eficaz es este Espíritu, o Palabra, o Testigo en el hombre,
para discernir los pensamientos e intenciones del corazón!
Cuán justo y preciso es al aprobarlos y condenarlos,
según sean buenos o malos, no sólo sin la ayuda del consejo o información humana,
sino a menudo en un desacuerdo directo con los sentimientos, consejos,
invitaciones y persuasiones de mis compañeros de juego,
e incluso de esos mucho mayores que yo,
quienes me declararon de forma confiada y repetitiva que éstas y otras cosas eran inocentes,
y para nada perversas, y que nadie las consideraba malas, excepto yo.
En verdad,
este testimonio de la Verdad se levantaba y vivía en mi corazón cuando era muy joven,
a través del resplandor de la luz divina o influencia del Espíritu Santo,
mostrándome aquellas cosas que eran malas y perversas.
Y a pesar de que todo lo que esos jóvenes pudieran decir en su contra,
yo creía que todas las personas buenas pensaban como yo.

Pero cuando se comete transgresión teniendo una clara convicción en la mente,
se experimenta la muerte, como ocurrió con Adán el día que comió del fruto prohibido.
Y en este estado de muerte, la verdad no se distingue tan fácilmente del error,
o el bien del mal, como antes de la transgresión. Los malos hábitos cobran fuerza;
la oscuridad entenebrece la mente; la tentación se renueva;
y aunque el Espíritu vuelve en cierta medida a advertir,
y a decir '`ten cuidado,`' la mente (acostumbrada a sofocar sus convicciones),
casi siempre se apresura a la desobediencia otra
vez y se vuelve cada vez más dura y oscura,
hasta que lo que fue claramente condenado como malo en el principio (por el Testigo
fiel en el corazón) finalmente se considera como inocente y sin pecado.
Esto es, a menudo, la trayectoria de la pobre humanidad.

Dios se manifiesta en el hombre a una temprana edad de la vida,
pero ellos suelen ser "`rebeldes a la luz`" que Él bondadosamente les ofrece.
Esto impide que "`conozcan sus caminos`" porque "`no moran en sus sendas.`"^
footnote:[Job 24:13 LBLA]
Y, ¿cómo es posible que conozcan el camino de la verdad,
o que crezcan en la sabiduría divina,
cuando pecan contra lo que Dios ya les ha dado a conocer?
Sí, viendo que han conocido a Dios (en algún grado) por Su resplandor en ellos,
pero que no Lo glorifican como Dios mediante su obediencia,
¿es de extrañar que se "`envanezcan en sus razonamientos,
y que su necio corazón se entenebrezca?`"^
footnote:[Romanos 1:19-21]
¿Y qué sucede después de esto?
Pues justamente lo que aparece en este pasaje de la Escritura;
porque una consecuencia muy natural de la rebelión es ser dejados en tinieblas,
y a menudo vemos que se comprueba entre los hombres, que, "`profesando ser sabios,
se hicieron necios.`"^
footnote:[Romanos 1:22]
"`Ya no somos tan ingenuos (creen ellos) como para pensar que esto y lo otro es pecaminoso.
¡Son pequeñeces!
Dios no toma en cuenta estos asuntos tan insignificantes.
Estos hombres cautelosos son demasiado escrupulosos.
Si ceden a todos estos temores vanos,
y se dejan atemorizar con pensamientos de maldad
en los diversos e inocentes pasatiempos de la vida,
pronto imaginarán que nada de este mundo es inocente.`"
Este (y otros similares) es el lenguaje de esa sabiduría que viene desde abajo,
que gobierna las mentes entenebrecidas de los que
transgreden las primeras convicciones de la verdad,
y se rebelan contra la luz del cielo.
Por el contrario, los que creen y caminan en la luz, mientras tienen la luz,
se convierten en verdaderos hijos de ella;
y en ella son hechos los alegres hijos del Día de la salvación de Dios.

Antes de llegar a los diez años de edad,
la obra de la verdad se hizo tan poderosa en mi mente,
que en varias ocasiones me propuse a enmendar mis caminos,
y a vivir una vida seria y religiosa.
Y aunque no era uno de los chicos más corruptos de mi edad,
era lo suficiente perverso como para ser sensible de los
juicios de Dios sobre mí por causa de la maldad de mis caminos.
Mi mente a menudo se turbaba extremadamente cuando
actuaba en contra de las manifestaciones divinas;
aunque todavía no tenía un sentido claro de que éste era el mismo poder
y Espíritu de Dios que tanto me condenaba y angustiaba por el pecado,
y se esforzaba por redimir mi alma de la esclavitud de la corrupción.

Entonces empecé a notar lo que la gente leía y decía respecto a la religión;
y entre otras cosas, en libros y conversaciones,
oí mencionar con frecuencia al Espíritu de Dios--cómo la
gente buena en los tiempos antiguos Lo tenían en ellos,
y por medio de Él aprendían la voluntad de Dios, y eran capaces de cumplirla.
Percibí que este Espíritu era mencionado a menudo
tanto en el Antiguo como en el Nuevo testamento,
y en muchos otros escritos, y comprendí que los verdaderos creyentes de estos tiempos,
también Lo tienen.
Pero, como muchos otros, menospreciaba sus vivas amonestaciones,
reprensiones y llamados dentro de mí;
y sin tener la menor idea de que había conocido algo de Él,
anhelaba la bendición de recibirlo,
suponiendo que aparecería de alguna manera extraordinaria,
muy diferente de todo lo que había conocido hasta entonces.

De la misma forma, los judíos, aún cuando esperaban la venida de Cristo,
no Lo conocieron cuando vino.
Ellos desestimaron y despreciaron Su apariencia humilde y ordinaria,
pensando que Él era hijo de José, y que había nacido de entre ellos,
y entonces Lo rechazaron, maltrataron, y finalmente Lo mataron.
Pero estaban equivocados con respecto a Su linaje; Su descendencia era del cielo;
y Dios (no José), era Su Padre.
De la misma manera,
miles hoy en día se equivocan en cuanto a la naturaleza
y origen del Espíritu de Dios en ellos.
Ellos piensan que eso que condena lo malo e invita a la justicia es del hombre,
algo que es parte de su naturaleza y ser; aunque esto precisamente es el don de la vida,
poder, y sustancia misma de Dios.
En verdad, Su origen es celestial, al igual que el Señor Jesucristo.
Él vino en esa apariencia mansa, humilde y ordinaria,
enseñándonos de este modo a no "`despreciar el día de las cosas pequeñas,`"^
footnote:[Zacarías 4:10]
ni a desestimar los pequeños movimientos de la vida divina en nuestras propias almas.
Y cuando Él comparó el reino de los cielos (que dijo
explícitamente que estaba dentro de nosotros^
footnote:[Lucas 17:20-21 "`El reino de Dios no vendrá con observación; Ni dirán:
Helo aquí, o helo allí; porque, he aquí,
el reino de Dios __dentro de vosotros está.__`" RV 1602 Purificada, LBLA (en el griego:
// lint-disable invalid-characters
ἐντὸς ὑμῶν ἐστιν)]) con las cosas externas,
enseñó a modo de instrucción que sus comienzos eran pequeños,
"`un poco de levadura,`" "`una semilla pequeña,`" "`un grano
de mostaza--la más pequeña de todas las semillas.`"
Esto es real en lo interno, independientemente de lo que entendamos de lo externo;
porque la semilla del reino es "`la más pequeña de todas las semillas`"
en el campo o en el jardín del corazón. Otras semillas brotan,
florecen, y llaman la atención,
mientras que "`la semilla incorruptible,`" "`la Palabra implantada`" en el corazón,
es despreciada, pisoteada, y menospreciada.

¡Oh! Que los niños y todas las personas tuvieran cuidado en sus primeros años,
y a medida que crezcan y avancen en la vida,
tengan en cuenta las "`reprensiones que instruyen`" en sus propios pechos;
porque ellas son "`el camino de la vida,`"^
footnote:[Proverbios 6:23 "`Porque el mandamiento es lámpara, y la enseñanza es luz,
Y camino de vida las reprensiones que te instruyen.`"]
es decir, vida divina para el alma.
Esta cosa que sienten en su interior--aunque no sepan qué es,
que los frena en secreto por el mal (tanto antes como después de que ceden a la tentación),
advirtiéndoles de antemano que no toquen, ni prueben, ni participen o cometan iniquidad,
y después condenándolos si lo hacen,
y también inclinándolos interiormente a una vida
de religión y virtud--esta es la cosa misma,
queridos jóvenes, por la que Dios obra en ustedes tanto el querer como el hacer.
Y por medio de ella, si se aferran a ella y obran con ella,
Dios les permitirá obrar su propia salvación con temor y temblor delante de Él.^
footnote:[Filipenses 2:12 RV1602 Purificada,
"`Obrad vuestra propia salvación con temor y temblor.`"]
No la desprecien, no contristen sus movimientos.
Ámenla, aprécienla, reveréncienla y escuchen sus convicciones.
Ríndanse sin demora a sus requerimientos y obedezcan sus enseñanzas.
Ella es el mensajero de Dios para el bien de sus almas inmortales.
Su voz clamando en las calles de sus corazones, es verdaderamente la voz del Dios vivo.
Su llamada, es una amable invitación para ustedes desde el trono de la gracia.
Escúchenla, y los guiará. Obedézcanla, y los salvará;
los salvará del poder del pecado y de Satanás. Y finalmente,
los conducirá a una herencia incorruptible en las mansiones de descanso,
la casa no hecha con manos, eterna en los cielos.

Si aman sus propias almas, y aprecian la salvación eterna, les ruego que me escuchen.
Es basado en mi experiencia de los terribles frutos de la desobediencia,
y de las aflicciones, remordimientos,
y sufrimientos de mi propia alma por el pecado y la transgresión que les hago esta advertencia.
Si yo hubiera obedecido fielmente a la verdad en lo íntimo;
si hubiera escuchado única y fielmente a este guía divino, mi porción habría sido la paz;
mi copa habría sido una copa de consolación. Podría haberme regocijado y cantado,
cuando en realidad he tenido que lamentarme y llorar.
Porque cuando había llegado a los quince años de edad (o un poco
más) en desobediencia a las claras convicciones internas,
y en oposición a las instrucciones del Espíritu Santo,
comencé a andar con personas muy libertinas, aprendí a bailar y a jugar cartas,
y me deleité mucho en ello.
A menudo me sentía profundamente condenado,
y con frecuencia me esforzaba por reprimir al Testigo interno,
y por persuadirme de que no había nada malo en ninguna de estas cosas.

Durante esos días, mi padre me reprendía en ocasiones por mi conducta,
pero pecar contra la luz divina y Sus visitaciones me endurecía contra sus consejos.
Me volví cada vez más vano, orgulloso, jovial, y descuidado.
Me puse en el camino de muchas malas compañías y
eso corrompió lamentablemente las buenas costumbres.
Mi gusto por el placer y el entretenimiento incrementó.
Mi estado de ánimo decaía cuando estaba solo,
y me precipitaba a la compañía y a la diversión en busca de alivio.

Así seguí divirtiéndome y jugando, gastando mi precioso tiempo en la vanidad.
A menudo por la noche, y algunas veces cerca del amanecer,
regresaba a casa después de mis alegres reuniones, sintiéndome condenado,
angustiado y avergonzado, deseando no haber ido con tal compañía,
y determinado a no hacerlo más. Pero mis determinaciones me fallaban muy pronto,
y volvía a lo mismo una y otra vez,
y así continué dando pasos cada vez más grandes en la insensatez que antes.
El Señor me seguía de cerca con misericordia, y a menudo irrumpía poderosamente en mí,
cambiando mi gozo en tristeza.
Pero aún así, pisoteaba al Testigo santo en mí,
hacía afrenta al Espíritu de gracia y regresaba a mis guaridas de diversión y alegría.

A veces, estando sobre la pista para bailar, con una pareja de la mano,
antes de que todos estuvieran listos,
Dios se levantaba en juicio y me golpeaba en el mismo corazón. Oh,
todavía recuerdo sensiblemente la majestad de Su aparición dentro de mí,
cuando nadie conocía la agonía de mi alma;
¡cómo Él levantaba repentinamente Su Tribunal en mi seno,
y con horror me hacía comparecer ante Él! Sentía que me
iba a hundir bajo el peso de la condenación y la angustia,
pero reuniendo con determinación todo el coraje que poseía,
hacía todo lo posible por ignorarlo, hasta que la música me llamaba a bailar.
Entonces ahogaba inmediatamente la voz de la convicción,
cobraba ánimo y me divertía entre mis compañeros en el desenfreno,
hasta que el tiempo puso un fin a nuestros encuentros festivos,
y me llamó a regresar (a menudo en soledad) a la casa de mi padre.

¡Ay de mí! ¿Cómo me fue entonces?
Te aseguro, lector,
que no he olvidado esas tristes y dolorosas caminatas de regreso a casa,
tras finalizar mis aventuras de medianoche.
Porque a veces era quebrantado y llevado a un profundo
abatimiento y aborrecimiento de mí mismo,
tanto que tenía que detenerme totalmente, sentarme en un tronco,
una piedra o un leño en el camino,
estrujar mis manos y derramar mis lágrimas delante
del Señor con mucho dolor y con extrema angustia,
estando cerca de la desesperación. Yo rogaba perdón, imploraba ayuda,
prometía enmendar mi camino,
obtenía algo de alivio y volvía a casa con la esperanza de cambiar.
Pero ¡ay, ay!
Mis determinaciones eran como si estuvieran escritas en la arena (por así decirlo).
Verdaderamente, el poder de la costumbre me había esclavizado,
y a menudo la siguiente invitación de mis compañeros
anulaba todas las promesas que recién había hecho.
El fervor de mis deseos por ir tras el entretenimiento y
la recreación hacía que quebrantara mis votos más sagrados,
y que me apresurara de nuevo a la transgresión, como un caballo se apresura a la batalla.
Una y otra vez, retomaba el baile y bebía hasta hartarme; y una tras otra vez,
el remordimiento y la tristeza se apoderaban de mí.

Pero ¡adorado sea para siempre el nombre del Señor! Él no me abandonó,
sino que me siguió cada vez más de cerca,
sonando la alarma cada vez más fuerte en mis oídos.
Había en mí una parte inmortal, hacia la que se dirigía su amor,
y cuya liberación (de las ataduras del pecado y de la corrupción)
Él buscaba con misericordia y con juicio,
con reprobaciones y con sonrisas, con castigos y con ternura,
y todo en un amor inexpresable.

Así trató conmigo.
Cuando me volvía a Sus reprensiones, me favorecía con Su gracia,
y aliviaba la ansiedad de mi alma; pero cuando volvía a rebelarme,
Su vara se alzaba en corrección paternal.
La apacible y delicada voz fue pronunciada en mi interior, como al aire del día,
cada vez que me encontraba un poco alejado del ruido y la conmoción--"`Adán,
¿Dónde estás tú?`" No había forma de esconderme del Él,
de cuyo ojo penetrante no se escapa ningún secreto,
y cuyo objetivo al reprender era sólo salvar.
Él seguía reprendiendo mis desvíos, y señalando el camino correcto,
según lo declaran las Escrituras, "`tus oídos oirán a tus espaldas palabra que diga:
Éste es el camino, andad por él.`"^
footnote:[Isaías 30:21 RVG]
Sin duda el camino me fue mostrado; a menudo era claramente puesto delante de mí,
pero yo no quería caminar en él. Conocía la voluntad de mi Señor, pero no la hacía;
todavía me deleitaba ser indulgente con mi propia voluntad.
¡Oh, que otros puedan escapar de la carga de mi culpa,
de mi lecho de infierno y de mi tormentosa agonía interna,
mediante una sumisión a tiempo a las reprensiones de la instrucción!

A veces gastaba casi todo el primer día de la semana (cuando
debería haber estado en las reuniones) jugando cartas,
en conversaciones ociosas (si no corruptas) y en otros vanos pasatiempos,
regresando a casa por la noche bajo un gran sentido de condenación. Aunque durante
todo este tiempo el Señor me preservó de tomar licores fuertes y de jurar,
sin embargo, me entregué en una considerable medida a las bromas, y conversaciones vanas,
y a veces me encontraba entre los peores de mis compañeros en discursos sucios y obscenos.
Entonces, nuevamente, me abrumaba una gran vergüenza y aborrecimiento de mí mismo;
y una vez más hacía un voto, prometía, y renovaba mi pacto; pero todo era en vano,
porque mis pactos no eran hechos ni renovados en la fuerza correcta,
sino que eran llevados a cabo en mi propias fuerzas y resoluciones humanas,
y por eso eran quebrantados rápidamente.
En ocasiones, me mantenía una o dos semanas, otras veces solamente un día o dos.
Así pasó el tiempo, y con el avance de los años,
encontré una tendencia creciente al descuido y al desenfreno.
Pero bendito sea el Dios de mi salvación,
pues Él incrementaba proporcionalmente mi sentido de culpa y condenación.

Experimenté temporadas de consideraciones muy serias acerca de la religión. Las instrucciones
externas que había recibido eran en su mayoría por medio de las reuniones de los Amigos,
pero cuando me acerqué a la adultez,
habiendo estado en compañía con algunos de la sociedad bautista,
me sentí inclinado a asistir sus reuniones en Providence.
Las reuniones de los Amigos eran por lo general llevadas a cabo en silencio,
lo que no satisfacía mi "`comezón de oídos.`"
Me encantaba escuchar palabras,
me volví más inquisitivo y comencé a investigar a profundidad las doctrinas y
principios de la religión. Los predicadores bautistas llenaron mis oídos de palabras,
y mi cabeza de argumentos y distinciones teológicas,
pero creo que mi corazón mejoró muy poco o nada mientras estaba con ellos.
Abandoné casi por completo las reuniones de los Amigos,
solo asistía a las reuniones anuales y a las reuniones designadas
por los ministros itinerantes al servicio del Evangelio.
Pero todavía recuerdo las impresiones celestiales y conmovedoras que a
veces recibía bajo los testimonios poderosos y vivificantes que se predicaban
con la evidencia y la demostración del Espíritu Santo,
y con la vida misma del evangelio, cuando iba a estas reuniones.
Aquí mi corazón era ayudado,
aunque mi mente era menos entretenida que cuando estaba entre los bautistas.
Sin embargo, como no sabía claramente cuál era la causa de esta diferencia,
y como aún deseaba la gratificación de los discursos argumentativos y sistemáticos,
continué asistiendo muy diligentemente a las reuniones bautistas;
y (en mis épocas más religiosas) comencé a pensar en ser bautizado en agua.

Debido a que la actividad mental sobrepasó por mucho la actividad del corazón,
mientras asistía a estas reuniones llenas de palabras,
me convencí de que esta ceremonia externa era una ordenanza de Cristo;
aunque desde entonces he visto, tan claro como la luz del día,
que el bautismo en agua nunca fue ordenado por Jesús,
sino que fue una institución introductoria, preparatoria, y decreciente;
y que ahora en la iglesia no hay más que "`un Señor, una fe, y un bautismo,`"^
footnote:[Efesios 4:5]--el del Espíritu Santo y fuego,
que es el único que puede purificar y limpiar lo interno.
Oh, mi corazón, mi propia alma está plenamente satisfecha en este asunto,
habiendo sentido la virtud viva de este único bautismo salvador,
y experimentado su plena suficiencia sin ningún otro.

Lo primero que hizo que mi mente creyera que el bautismo externo era una ordenanza cristiana,
fue este argumento de los bautistas: --"`Cristo ordenó a Sus discípulos que bautizaran;
ningún hombre puede bautizar con el Espíritu Santo; por lo tanto,
el bautismo que Él ordenó no fue el del Espíritu Santo, sino el bautismo de agua.`"
En aquel entonces esto me parecía contundente e incontestable.
Pero fue mi ignorancia acerca de ese poder (que bautiza y que acompaña a todo verdadero
ministerio evangélico) lo que me hizo asentir a la postura falsa de que,
"`ningún hombre puede bautizar con el Espíritu Santo.`"
Sé que el hombre mismo, en su propia capacidad, no puede; pero también sé,
que por sí mismo tampoco puede anunciar el evangelio.
La afirmación "`ningún hombre puede anunciar el evangelio,`" es tan cierta
como la de que "`ningún hombre puede bautizar con el Espíritu Santo.`"
Como hombre, no puede hacer ninguna de las dos cosas.
Pero sigue siendo cierto que el hombre puede, y hace ambas, a través de la ayuda divina.
El verdadero evangelio nunca fue predicado,
sino "`por el Espíritu Santo enviado del cielo.`"^
footnote:[1 Pedro 1:12]
Así lo predicaron los apóstoles, y así debe ser predicado en este día;
y cuando se predicaba de esta manera, era verdaderamente un ministerio que bautizaba.
Mientras hablaban, el Espíritu Santo caía sobre los que los escuchaban; es decir,
donde la Palabra eterna y viva era predicada y se "`mezclaba con fe en los que la oían,`"^
footnote:[Hebreos 4:2 RVG]
el Espíritu Santo caía sobre ellos,
bautizándolos en un sentido vivo del "`poder de Dios para salvación,`"^
footnote:[Romanos 1:16]
que es la verdadera vida del evangelio.
Así, los apóstoles cumplieron su comisión; a saber, ellos con su enseñanza bautizaban.
La comisión no fue, "`enseñen,
y luego bauticen,`" como si fueran dos actos independientes;
sino "`enseñad a todas las naciones, bautizándoles dentro del nombre.`"^
footnote:[Mateo 28:19 Reina Valera Gomez, y Reina Valera 1602 Purificada.
El Griego no se lee como "`bautizándoles en el nombre,`"
sino "`bautizándoles dentro __+++[+++eis+++]+++__ del nombre.`"]
El acto es uno y el mismo;
y los que son testigos vivos del Evangelio (el poder
de Dios para salvación) que se les predica,
lo sienten y lo reciben; son enseñados en este bautismo,
"`con demostración del Espíritu y de poder.`"^
footnote:[1 Corintios 2:4]

Estoy completamente convencido de que el uso del bautismo en agua,
después de la resurrección de Cristo, fue simplemente en condescendencia^
footnote:[En un sentido positivo que denota paciencia, tolerancia, compasión,
misericordia, etc.]
hacia el pueblo;
porque mientras que el velo se mantenga sobre el entendimiento de las personas,
no pueden ver claramente la espiritualidad de la dispensación del evangelio;
ni entender por qué las cosas viejas de Juan el Bautista y de Moisés no
dejaron de usarse inmediata y totalmente tan pronto como fueron cumplidas.
Aunque para el ojo que ha sido abierto, esto no es nada misterioso;
ni podría haber sido de otra manera, pues se requiere de un gran cuidado, precaución,
y moderación,
dejar de lado correctamente estas prácticas religiosas que han sido cumplidas y superadas.
La práctica de la circuncisión también continuó por un número
considerable de años después de la ascensión del Señor Jesús,
y se tenía en tan alta estima,
que algunos de la iglesia de Judea se ofendieron en gran
manera con Pablo porque no la predicó entre los Gentiles.
De hecho,
muchos Judíos Cristianos eran tan celosos de las ceremonias de la ley
de Moisés (incluso unos veinte años después de la resurrección de Cristo),
que temían que la presencia de Pablo en Jerusalén fuera ofensiva para los hermanos,
a menos que se sometiera a los ritos de purificación,
de una manera que demostrara que "`andaba ordenadamente, guardando la ley.`"^
footnote:[Hechos 21:24]
Así,
vemos lo difícil que fue abandonar las prácticas de la circuncisión
y el bautismo en agua por completo de una sola vez.
El pueblo apenas podía soportarlo,
y la prudencia requería mucha condescendencia e indulgencia por un tiempo,
en cuanto a la continuación de estas y otras sombras externas.

Ahora, volviendo a mis primeros ejercicios sobre el bautismo en agua.
Durante ese tiempo, no podía convencerme de que yo era digno de ello.
Pensaba que era una ordenanza sagrada, que nadie tenía derecho de realizar,
excepto aquellos que (como ahora lo puedo ver) no tienen necesidad de ella, es decir,
aquellos que habían recibido primero su cumplimiento y antitipo,
el bautismo salvador de Cristo.

Aún no me había entregado por completo a los movimientos de la vida divina
en mi propio corazón. Mi mente estaba demasiado vuelta hacia lo externo,
y la predicación de los que a veces iba a escuchar (que predicaban en
su propio tiempo) tenía una poderosa tendencia de mantenerla en lo externo.
En este estado de atención y búsqueda en lo externo,
no encontré nada que pudiera darme poder sobre el pecado y la corrupción;
y a pesar de todas mis consideraciones serias,
y de mis frecuentes y ardientes deseos de volverme verdaderamente piadoso, aún así,
de vez en cuando, abandonada mis esfuerzos,
y me lanzaba a los mismos grados de vanidad y maldad de siempre.

En una ocasión, estando bajo un profundo ejercicio,
tras razonar y dudar por una gran parte del día sobre si era mejor
entregarme con todo mi corazón a llevar una vida religiosa o no;
finalmente cedí,
y entré una vez más en un pacto solemne de servir a Dios y negarme a mí mismo,
de acuerdo a lo mejor de mi entendimiento.
Pero casi inmediatamente después de haberme entregado
a Dios y llegado a esta buena conclusión,
el gran adversario entró,
confundió y angustió excesivamente mi mente con la doctrina de la predestinación;
insinuando poderosamente que un cierto número estaba
infaliblemente destinado a la eterna salvación,
y el resto a la inevitable destrucción;
y que todos los esfuerzos religiosos de mi mente no podrían
alterar de ninguna manera mi porción y destino final.
Pensé, si Dios me ha condenado desde toda la eternidad,
necesariamente estaré condenado para siempre;
y si me ha escogido para la salvación eterna, puedo dejar que mi corazón descanse,
y vivir la vida de manera que más gratifique mis inclinaciones naturales.
Porque, ¿qué ventaja podría haber en llevar una vida rigurosa de pureza y abnegación,
si un decreto eterno e inalterable ya había asegurado mi salvación?
Me sentía dispuesto a esperar que yo fuera una vasija escogida;
y por un corto tiempo estas ideas absurdas (¿y acaso
no puedo decir blasfemas?) llenaron mi mente,
hasta el punto de estar dispuesto a concluir que el Dios de toda bondad
había condenado a la mayor parte de la humanidad a una miseria interminable,
sin ninguna provocación de parte de ellos.
Ahora veo la doctrina de la elección y la reprobación incondicionales con aborrecimiento,
y me asombra que aún estando bajo una nube de tinieblas,
mis facultades racionales pudieran asentir a una idea tan monstruosa.

Permanecí en esta
condición por solo unas pocas semanas cuando,
lamentablemente, la influencia de la compañía de jóvenes,
y mis deseos vehementes de indulgencia carnal, rompieron todos mis votos solemnes,
derribaron mis muros y fortalezas,
y me expusieron como presa fácil al gran enemigo de la salvación de mi alma.
Una vez más me dejé llevar por la vanidad, los entretenimientos, y el desenfreno.
Sin embargo, aunque este episodio fue corto, fue uno bastante miserable.
El Señor, en su incomparable bondad,
me siguió con Sus juicios que se revelaron internamente en contra del pecado.
El príncipe de las tinieblas también me siguió, con tentación tras tentación a la maldad,
y con varias insinuaciones sutiles y oscuras nociones, para privarme de todo temor,
restricción, o ternura de consciencia.

Al final, a pesar de todo lo que había sentido del poder de Dios sobre mí,
al reprobarme por el pecado e invitarme a la santidad,
el Santo Testigo se contristó tanto dentro de mí,
que empecé a entretenerme con la idea de que no había Dios,
que todas las cosas se producían, por casualidad, por causas naturales,
por la acumulación y fusión al azar de átomos, sin ninguna causa,
planificación u organización inteligente.
Aquí debe considerarse bien, cómo la aceptación de una falsa doctrina,
y la transgresión de la manifestación y convicción divina en mi consciencia,
preparó el camino para otras doctrinas falsas.
Porque no mucho tiempo después de haber recibido
y atesorado la doctrina de la predestinación irresistible,
la niebla de las tinieblas se esparció sobre mi mente de tal manera,
que no solo me atreví a negar la Deidad eterna,
sino que (¡pensar en ello es horrible!) también comencé a regocijarme
en la idea de un libertinaje y una carnalidad sin límites ni restricciones,
y de que nadie me pediría cuentas por mi conducta.

¡Oh, entonces qué depravación del gusto y de los deseos, así como del entendimiento,
en la que estaba sumido!
Estoy tan asombrado ahora de que haya podido desear que no existiera Dios,
como de que haya podido creer en un absurdo tan inconcebible.
Una noche, en compañía de algunos de mis alegres amigos,
conversamos sobre varios asuntos, hasta que al final les presenté mi nuevo tema,
para ver qué proponían en contra de él. Y como no estaba dispuesto
a que ellos supieran la seriedad con la que consideraba la idea,
la presenté como una mera suposición, declarando que (a modo de argumento),
trataría de demostrar por medio de la razón, la inexistencia de Dios,
más claramente de lo que ellos podían mostrar la existencia de uno.
Algunos de mis compañeros pensaron que mi excentricidad y mi presunción eran muy extrañas;
varios se rieron de mis tonterías;
y otros se mostraban complacidos con la novedad de mi idea.
Después de un tiempo la dejamos de lado,
pero el temor y la condenación pronto se apoderaron de mí,
incluso antes de dejar a mis alegres compañeros.
Hice todo lo posible por reírme y aplacar mis temores;
pero mi corazón temblaba con asombro al pensar lo lejos que había llegado,
y qué podía ser de mí. Me despedí de mis amigos,
y regresé a casa en gran agonía de espíritu.
Y ahora creo que sería extremadamente cruel si deseara
que mi mayor enemigo soportara el miedo,
la ansiedad, y el asombro, que pasé durante esa noche,
tanto en mi viaje de regreso a casa como después de llegar.
Apenas me atrevía a entrar en mi dormitorio, no fuera que de repente,
y de una manera terrible,
fuera llevado a juicio y castigado por causa de mi osadía e insensatez.
Oh joven, quienquiera que seas que leas estas líneas, te advierto, te suplico:
evita tal miseria obedeciendo a tiempo;
evita tal angustia indecible aferrándote al Señor,
porque es cada vez más difícil doblegar la voluntad,
después de que se ha endurecido tras no hacer caso
a las manifestaciones vivas del Espíritu de Verdad.

Continué de la misma manera, por unos meses más. Gasté mis días en vanidad y rebelión;
y mis noches, a menudo, en horror y angustia.
Dondequiera que fuera, la condenación iba conmigo.
Mi acusador, y sin embargo mi mejor amigo, yacía cerca de mi pecho,
y mientras continuaba rebelándome, Él me atormentaba tanto de noche como de día;
pero todo esto lo hacía con tierno amor, con el fin de redimir mi alma preciada,
y rendir mi obstinada voluntad a la obediencia de la cruz.
Sí, tengo el fundamento más firme para creer que fue el verdadero poder de Dios sobre mí,
el que expuso así mis pecados delante de mí,
y contendió conmigo para que regresara a Él y viviera.

Continué de este modo hasta el invierno del año 1770,
cuando teniendo cerca de diecinueve años,
me convencí más plena y claramente (por las operaciones,
iluminaciones y revelaciones que venían directamente de la luz divina en mi propia
mente) de que este _algo interno_ que había contendido larga y poderosamente conmigo,
perturbando cada uno de mis reposos falsos,
refutando cada imaginación falsa y pecaminosa de carne y sangre, o del gran adversario,
y también mandándome a renunciar a todo,
y a caminar por los caminos de la virtud y de la verdadera abnegación,
era el Espíritu y poder verdadero y vivo del Dios
eterno--el mismo que contendió con el mundo antiguo,^
footnote:[Génesis 6:3]
influenció a los patriarcas, profetas, y apóstoles, y aún visita, contiende,
y en ocasiones influencia (en mayor o menor medida) los corazones de toda la humanidad.
Ahora podía ver que este es el único poder que es
capaz de obrar la verdadera conversión y salvación,
y comprendí que, mientras sea resistido y rechazado,
debe permanecer inevitablemente una separación entre Dios y el alma;
pero cuando este poder es recibido,
y el corazón se somete verdaderamente a él en todas las cosas,
ocurre una reconciliación completa.

La verdadera religión o regeneración es una realidad;
y toda su realidad sustancial se concentra en una palabra--"`Emanuel,`" esto es,
"`Dios con nosotros.`"
Y hasta que no se experimente de manera viva algo de esta unión,
no se sabe nada de la verdadera religión. El mundo,
bajo las diversas formas de profesión religiosa, se entretiene con sueños, métodos,
e imaginaciones, mientras que "`la única cosa necesaria`" es muy poco experimentada.
La única cosa necesaria es una unión genuina con Dios,
una unión real con Él en el único Espíritu.
Sin esta unión, deja que un hombre sepa lo que quiera; que crea,
posea y disfrute de todo lo que pueda,
aún así no es más que un extranjero y un errante sobre la tierra.
Nada más puede satisfacer su alma, o servir para aquietar su mente.
No existe otro descanso permanente para la planta de sus pies.
Puede esforzarse, trabajar y afanarse,
y muchos pueden pensar que está en un estado de alegría;
pero todo es un engaño. En medio de todos los placeres de la tierra,
si él presume en declararse a sí mismo feliz,
lo hace contradiciendo tanto la verdad como sus propios sentimientos,
y el que es verdaderamente sabio, podrá ver a través de la mentira.
Si él profesa la religión, asiste a reuniones, practica la adoración de manera externa,
y habla bastante acerca de la fe y la piedad,
puede (tan solo por un tiempo) acallar su mente y engañar a su propia alma y la de otros;
pero no podrá descansar tranquilamente mucho tiempo sin una verdadera unión con Dios.
Puede que se vuelva a la derecha y a la izquierda, mirar a un lado y a otro,
buscar satisfacción en la sociedad, en gratificaciones sensuales, en la riqueza,
el honor y los logros terrenales; o incluso puede leer, orar, meditar, cantar, escribir,
y sumergirse profundamente en una devoción humana; pero sin esta unión viva,
está perdido, sin ancla, "`miserable, pobre, ciego y desnudo.`"^
footnote:[Apocalipsis 3:17]

Habiendo finalmente llegado a la convicción real de que era nada
menos que el eterno poder y Espíritu de Dios el que tan eficazmente
obró en mí para librarme del poder de las tinieblas y la seducción,
me sentí capacitado para rendirme ante los santos requerimientos de Dios,
conforme me eran mostrados internamente.
Nada más podría haberme abierto la mente de tal manera y darme a conocer mi deber.
Las Escrituras, otros libros buenos, el ministerio evangélico,
las conversaciones religiosas,
las meditaciones sobre las obras de la creación y la providencia--todos
estos son muy buenos medios de información;
pero ninguno de ellos,
ni siquiera todos juntos (sin la operación y la evidencia
del Espíritu Santo sobre la mente),
pueden hacer que un hombre esté seguro de su deber para con Dios en cualquier cosa.
Puede razonar, y establecer muchas reglas, medidas, y estándares del deber y la moral;
pero nunca llegará a la certeza sin la ayuda de esa Luz que en sí misma es cierta.
Se puede decir que las Escrituras son ciertas.
Muy bien, pero ¿qué te garantiza que son ciertas, o que conoces su verdadero significado?
¿Acaso no difieren ampliamente los que se llaman maestros en el
razonamiento con respecto a muchos pasajes en las Sagradas Escrituras?
¿Y no dicen todos que tienen la razón de su lado?
Pero no les creas, sin la luz y la evidencia de Espíritu Santo.

Pero para continuar--me entregué completamente y de corazón a servir
al Señor en el camino de Su guía. Abandoné
las compañías de personas groseras y corruptas,
me aparté al retiro, asistí a las reuniones de los Amigos,
y a menudo busqué al Señor y esperé en Él a solas, en silencio solemne y reverencial,
buscando Su consejo, dirección,
y preservación. Y Él se complació en señalarme el camino y ponerlo delante de mí,
mostrándome una cosa tras otra, con suficiente claridad.
Primero, me mostró lo que no debía hacer en varias cosas específicas,
separándome de mis prácticas y compañías corruptas.
Esto era abandonar el mal.
Y luego, Él me enseñó y me dirigió en la práctica de varias cosas particulares,
mostrándome que debía elegir y unirme a eso que es bueno.
Vi claramente, que era Su voluntad, y mi deber indispensable,
reunirme reverentemente con Su pueblo para la divina adoración, y allí esperar en Él,
acercarme internamente a Él,
y (según el lenguaje del apóstol en Hechos 17:27) palpar a fin de poder hallarle y disfrutarlo.
También a menudo encontré que mi deber era esperar en Él a solas,
en un retiro silencioso; no acercándome a Él con súplicas,
excepto cuando Él influenciaba mi corazón a hacerlo con
el verdadero Espíritu de oración e intercesión.

Además, me mostró que la religión era una vida interna en el alma,
y que una gran atención, sinceridad, y diligencia,
eran necesarias para su crecimiento y prosperidad.
Vi que no debía estar satisfecho con asistir a las reuniones y sentarme en silencio,
aunque lo hiciera de la manera más reverente y adecuada,
sino que debía vivir continuamente en una vigilancia
interna y en una dedicación de corazón,
vigilando todos mis pensamientos, palabras, y acciones,
experimentando todas las cosas dentro de mí llevadas a juicio,
sin permitir que nada pasara sin ser examinado.
Me mostró que debía mantener la más recta honestidad
y sinceridad en todos mis tratos con los hombres,
como en presencia de Dios,
quien es testigo de todas mis acciones externas y pensamientos internos.
Me enseñó que los hombres generalmente confían demasiado
en los actos y apariencias externas.
Y así, guardando mi mente de pensar demasiado en cualquier cosa externa,
Él abrió mi entendimiento y me permitió ver mi deber con respecto a la
sencillez externa--haciéndome ver que una vestimenta y forma de vida sencillas,
decentes,
y no costosas (en todos los aspectos) concordaban
con la verdadera seriedad y abnegación Cristiana;
y que una vestimenta, una casa, una comida o muebles lujosos, llamativos, o a la moda,
alimentaban y fomentaban el orgullo y la ostentación en el corazón, robaban a los pobres,
complacían a los vanidosos, y conducían a una gran cantidad de cuidados,
trabajos y preocupaciones innecesarias para mantener este modo de vida y apariencia.
Vi cómo tales cosas no ofrecían ninguna satisfacción verdadera y sólida,
sino que inevitablemente sacaban la mente de la vigilancia interna y cuidadosa,
obstaculizando la obra de la cruz y la verdadera abnegación,
y facilitando las relaciones y amistades infructuosas con
hombres que preferirían alejar sus afectos de Dios,
que unir sus almas a Él.

Enseñado de esta forma, me incliné en reverencia;
y como de vez en cuando era necesario comprar ropa,
me esforcé para que mi apariencia externa estuviera
en conformidad con los decretos de la verdad,
en lo que encontré verdadera paz y satisfacción. Además,
Él me instruyó a usar el lenguaje simple de las Escrituras,
usando la forma del "`tú o usted`" con una persona
y la de "`vosotros o ustedes`" con dos o más.^
footnote:[La mayoría de los angloparlantes modernos desconocen
que las palabras "`you`" y "`your`" eran originalmente pronombres
_plurales_ que se utilizaban sólo para dirigirse a dos o más personas,
mientras que "`thee`" y "`thou`" se usaban para dirigirse a una sola persona.
En el siglo XVII, se puso de moda
(originalmente con el fin de mostrar honor o adulación)
utilizar el plural "`you`" y "`your`" (como "`vosotros`" o "`ustedes`")
para dirigirse a una sola persona singular de mayor estatus social,
mientras que "`thee`" y "`thou`" (como "`tú`" y "`usted`") se reservaban para los sirvientes,
los niños o las personas de menor posición social o económica.
Los amigos se apegaron a lo que entonces se consideraba "`lenguaje simple`"
(utilizar el pronombre tú y usted cuando se dirigían a una persona singular,
y el pronombre vosotros y ustedes cuando se dirigían a dos o más),
en lugar de mostrar preferencia al dirigirse a ciertos individuos en plural.]
La cruz me era de gran tropiezo en relación con estas cosas.
El asunto del lenguaje, en particular,
parecía tan insignificante y tonto para la sabiduría terrenal que había en mí,
y el miedo a la risa del mundo se oponía tan poderosamente,
que cedí al razonamiento carnal.
¿De qué puede ser útil esta pureza del lenguaje?
¿No podré servir a Dios de una forma menos extraña y despreciable,
en lugar de involucrarme en esas cosas que ciertamente me convertirán en un ridículo?
El mundo no puede ver en esto más que capricho y superstición;
y ¿qué tan útil puede ser un hombre para los demás si su
inconformismo lo excluye de ser considerado de forma favorable?
Y si esto no perjudica a los demás, ¿dónde está el perjuicio para mí, como individuo,
de seguir en mi lenguaje habitual?
Razonamientos como estos, y muchos más,
se presentaron en oposición al requerimiento sagrado.
Pero el Señor me mostró, que, si quería "`ser sabio,`" debía "`hacerme ignorante.`"^
footnote:[1 Corintios 3:18]
Si quería ser Su discípulo, debía primero negarme a mí mismo,
tomar la cruz diariamente en lo que Él me requiriera,
y seguirlo en el camino de Sus enseñanzas.
Fue duro y doloroso para mi voluntad natural ceder ante este deber.
Pensé que,
si el sacrificio de mi mano derecha excusara mi cumplimiento de este requisito,
lo ofrecería con gusto, antes que resignarme a usar una forma de hablar tan despreciada,
y someterme a que se burlaran de mí como alguien que consideraba
que la religión se trataba de cosas tan pequeñas como éstas.

Este ejercicio me atormentó día y noche por algún tiempo,
durante el cual derramé muchas lágrimas de dolor y angustia, alegué muchas excusas,
y anhelé en gran manera que se aceptara algún substituto en lugar
de lo que se me requería. Pero Aquel que me llamó a llevar a cabo
estas locuras (locuras para la sabiduría del mundo),
se complació misericordiosamente en mostrarme con incuestionable claridad,
que Él escogería Su propio sacrificio; y que ni una mano derecha u ojo derecho,
ni millares de carneros, o diez mil arroyos de aceite,
servirían de ninguna manera en lugar de Sus requerimientos.
Si Él me llamó por algo tan débil o insensato como las palabras "`tú`"
y "`usted`" para una sola persona (en lugar de vosotros y ustedes),
ninguna otra cosa que yo sustituya servirá en lugar de eso;
porque "`lo insensato de Dios es más sabio que los hombres.`"^
footnote:[1 Corintios 1:25]
Que nadie discuta este terreno con el Omnipotente, ni consulten con carne y sangre;
no sea que, por despreciar el día de las cosas pequeñas, caigan poco a poco.
Porque tengan por seguro, oh ustedes que son llamados por el Señor,
a menos que obedezcan Su llamado, y salgan de todo lo que Él los ha llamado a salir,
nunca podrán llegar a ser Sus elegidos.
Si no son fieles en lo poco, tampoco podrán serlo en lo mucho.

Quizás pocos creerán la plenitud del gozo celestial que brotó en mi seno,
como un manantial de aguas vivas,
después de que por fin me entregué en fidelidad a este requerimiento.
Sin embargo, este fluir de consuelo divino no duró por mucho tiempo; porque,
aunque renuncié a todo lo que el Señor demandaba de mí,
puesto que me había rebelado por tanto tiempo y con tanta dureza contra Él,
vio oportuno poco tiempo después, en Su infinita sabiduría,
ocultar Su rostro de nuevo de mí, y encerrarme en una oscuridad casi total,
que hizo que mis días fueran verdaderamente tediosos
y mis noches agotadoras para mi alma.

Estaba completamente convencido de que Dios debía ser conocido internamente,
en poder y en gran gloria,
por los que Lo obedecen y esperan en Él. Mi corazón ardía
de amor hacia Él. Había visto un poco de Su belleza,
y Él se había convertido en el amado de mi alma, distinguido entre diez mil.
Por lo tanto, a menudo me retiraba a la soledad, y en profundo y reverente silencio,
Lo buscaba, y rogaba con insistencia por un conocimiento más íntimo con Él. Pero,
sabiendo lo que era mejor para mí,
Él ocultó (en misericordia) Su presencia de mí. Y aunque esta fue una época dolorosa,
siempre sentí inquietud si dejaba de buscarlo.
Así proseguí con mis ardientes acercamientos en silencio, o tiempo de espera.
En verdad, esperé con toda la reverencia, humildad,
y cuidado de la que mi alma era capaz; pero todo parecía en vano.
No pude ver ninguna chispa o rayo de luz,
ningún destello del favor de Dios hacia mí. ¡Oh, el luto y la lamentación,
la angustia y el amargo llanto,
que me abrumaban continuamente durante varios meses por falta de la presencia
de mi Dios que vivifica mi alma! "`¡Oh!,`" dije en mi corazón,
"`¿Nunca se levantará Él para ayudarme y liberarme?
Bueno, pase lo que pase, lo buscaré hasta el día de mi muerte;
mi alma no puede vivir sin Él;
y aunque Él esconda Su rostro de mí hasta el último momento de mi vida,
puede que me acepte en ese final solemne y me reciba en la gloria.`"
Este era a menudo, muy a menudo, el lenguaje de mi corazón;
y bajo esta resolución seguí adelante en la amargura de mi alma.
Estoy seguro de que el ajenjo y la hiel, la angustia y los suspiros,
los días y las noches de angustia difícilmente serán olvidados.
Me parece que ciertos lugares de la tierra, algunos campos y arboledas particulares,
continuarán siempre (mientras la vida y la sensibilidad permanezcan)
ejerciendo una influencia que conmueve y afecta mi mente,
cada vez que paso y los veo, o los recuerdo.
En realidad,
permanecen singularmente distinguidos en mi memoria por las lágrimas y los gemidos,
los suspiros y las súplicas de los que han sido testigos silenciosos.

¡Oh, mi Dios!
Me guiaste por el desierto.
Me destetaste del mundo, y me atrajiste al desierto.
Allí, escondiste Tú rostro de mí durante un tiempo;
hasta que se encendieron intensamente los deseos de mi alma por Ti. Entonces,
Tú levantaste mi cabeza y me hablaste de manera consoladora;
¡bendito sea Tu santo nombre por siempre!

Al final, después de que el Padre de misericordias me probó de esta forma,
Él se apiadó de mí y me miró con compasión,
escuchó la voz de mi angustia y desnudó su santo brazo para
mi liberación. Poco a poco me develó Su santa presencia,
y abrió mi corazón para entender por qué me condujo a través de una temporada tan difícil.
Empecé a discernir en el misterio,
lo que había leído en la historia del peregrinaje
de Israel en el desierto durante los cuarenta años,
y también la "`voz del que clama en el desierto.`"^
footnote:[Isaías 40:3; Mateo 3:3]
Comencé a ver la necesidad de que el Señor enviara a Su
mensajero para que preparara el camino delante de Él,
y se enderezara las calzadas.
Percibí cuántas cosas ásperas, desniveladas y torcidas había en Su camino,
y entonces comencé a entender y (en cierta medida) a amar la vara,
y a Aquel que la había designado.
Y a medida que el Maestro se manifestaba más y más,
comprendía cada vez más Sus misteriosas maneras de obrar.

Después de un tiempo,
el Señor abrió mi entendimiento para comprender las abundantes pruebas, experiencias,
peligros y liberaciones de Sus seguidores en épocas pasadas;
y se encendió en mí la esperanza de que ahora podría continuar
sin toparme con tales asedios y retiros de la luz,
como sucedió previamente.
Porque, aunque el Señor aún se retiraba de mí en ocasiones, sin embargo,
debido a que no tardaba mucho en volver,
y Su presencia estaba mucho más constante conmigo,
estaba listo para concluir que esto podría continuar con un resplandor creciente,
hasta que yo fuera completamente absorbido en Su amor.
Y, al no tener un entendimiento claro del consejo de Su divina voluntad,
me inclinaba a desear que ésta fuera mi condición constante,
no viendo (como he podido ver desde entonces),
que no era del todo bueno para mí experimentar un estado constante de sol y buen tiempo.
Incluso el orden y la dirección externos de la providencia
divina en la naturaleza nos proporcionan una enseñanza,
que a menudo se aplica maravillosamente a nuestras experiencias internas.
No siempre hay calma y sol.
De hecho,
la sabiduría divina decreta muchos y grandes altibajos y cambios en el mundo natural,
de tal manera que, tal vez en la estación más agradable y próspera del año,
después de unos días muy despejados y tranquilos, se levanta la más terrible tormenta,
con viento, relámpagos, truenos y granizo.
En otras ocasiones, vientos fuertes y precipitados llegan después del día más tranquilo,
o las sequías más intensas siguen a la estación más fructífera.
Incluso el orden establecido y la sucesión de las estaciones
es una revolución continua del día y la noche,
del verano y el invierno, de la siembra y la cosecha.
Tenemos frío y calor, oscuridad y luz, heladas cortantes y los rocíos más refrescantes,
y una variedad de otros cambios.
Todo esto ocurre en la infinita sabiduría y bondad,
y muestra al ojo que discierne el poder y la gloria del gran Superintendente.
Inclínate, ¡oh alma mía! Adora y alaba al Dios de tu vida,
quien es la prolongación de tus días, y tu porción para siempre.
Sus obras son admirables, inescrutables, maravillosas,
y más allá de tu comprensión. Ves en parte la multitud
y magnitud de Sus maravillosas obras;
contemplas una pequeña parte de los cambios y fluctuaciones que las acompañan; y,
sin embargo, ¡con qué excelente orden, armonía, y constancia son conservadas!
Indudablemente,
nada menos que la omnipotencia unida a la omnisciencia
podría efectuar o producir todo esto.
Y aunque Él puede ejercitar las almas de Sus elegidos
con varios y dolorosos tiempos de prueba,
sí, incluso "`escogerlos en el horno de aflicción,`"^
footnote:[Isaías 48:10]
sin embargo,
Su amor hacia ellos no puede fallar más de lo que el día y la noche pueden cesar,
o Su pacto con ellos ser anulado.
Es tanto en sabiduría y bondad que Él algunas veces (por así decirlo) se retira,
se esconde, y deja a Sus hijos,^
footnote:[2 Crónicas 32:3; Isaías 8:17, etc.]
y luego regresa gloriosamente para su indecible consuelo,
como ocurre con la sucesión de las tinieblas y la luz, y las estaciones frías y cálidas,
en el mundo externo.

Es necesario padecer muchas y diferentes aflicciones para nuestra purificación.
Es por esto que el lugar de este refinamiento es llamado "`el horno de aflicción.`"^
footnote:[Isaías 48:10]
A través de las operaciones purificadoras de estas pruebas de fuego,
el alma es redimida gradualmente del pozo de la contaminación.
Y quien conozca a fondo las corrupciones de la naturaleza humana,
en su alejamiento de Dios,
descubrirá (si es que alguna vez se produce una verdadera humillación y renovación
en él) que solamente el bautismo del fuego puede verdaderamente limpiar lo corrupto,
y humillar el corazón orgulloso del hombre caído. Esto es sin duda una verdad sellada,
que los que se dejan sin disciplina son bastardos, y no hijos.
"`Porque el Señor al que ama, disciplina, y azota a todo el que recibe por hijo.`"^
footnote:[Hebreos 12:6]
Mi alma se regocija y da gracias a Dios por las profundas pruebas y retiros de Su presencia;
como también por las experiencias discernibles de Su amor y los
levantamientos de la luz de Su rostro sobre mí. Veo y reconozco
lo necesario que esto es para mi crecimiento en la vida divina,
así como para mi completa liberación de la servidumbre del pecado,
que Él trate conmigo de esta manera;
y me ha servido de instrucción el hecho de que Él
sea llamado en las Escrituras por el nombre de "`Jehová,
el cual esconde su rostro de la casa de Jacob.`"^
footnote:[Isaías 8:17]
Oh, qué gran clamor del alma, qué ansioso anhelo por Su regreso,
toman lugar en todos los verdaderos viajeros, cada vez que Él vela Su santa presencia.
¡Y qué gozoso es cuando el Señor, después de estas estaciones,
alza Su rostro sobre la mente abatida que ha sido
preparada de esta forma para Su reconfortante regreso!
Es como el regreso del claro brillo del sol después de la lluvia.

Bajo la mano purificadora del poder de Dios, por la que humilló y abatió mi alma,
fui capaz de ver claramente la necesidad que tendría de esta excelente
cualidad--la humildad--en mi progreso a lo largo de la vida religiosa.
Vi claramente, incluso en medio de mi más profunda depresión, que,
si yo fuera favorecido con una paz continua y un gozo divino incesante,
estaría en peligro de orgullo y exaltación espiritual.
Bendito sea el nombre del Señor por este favor entre muchos
otros--que me enseñó la necesidad de la humildad y así me
previno y preparó contra las artimañas de satanás. Oh,
cuán ardiente era el deseo de mis oraciones que subían ante Él para que
Él reprendiera al orgulloso espíritu de Lucifer que había en mí,
y designara mi morada en el valle de la humillación,
donde la hierba es verde y donde las flores fragantes dan un aroma agradable.
Vi que sobre el monte alto a menudo reinaba la esterilidad y la
desolación. Así que mi mente estaba casi constantemente impregnada
en aquellos días con un amor y un deseo por una profunda humildad.
Vi algo de su verdadera belleza, y la anhelé como una de las mayores bendiciones.
"`Oh,`" dije, "`¡que pueda ponérmela como una vestimenta,
y llevarla puesta para siempre!; sí,
¡incluso presentarme en ella ante mi Juez en la asamblea de los
santos y los ángeles en los días venideros!`" "`Oh Señor,
Dios mío,`" fue entonces mi lenguaje, y mi corazón se une ahora a él,
"`no me permitas olvidar mis tribulaciones,
¡ni que cesen mis oraciones hacia ti para que se mantenga esta preciosa humildad!
Que ésta sea la primera y la última en la lista de mis peticiones.`"

Así, el gran Líder de Israel me guio paso a paso;
no por medio de un constante e ininterrumpido gozo de Su presencia,
sino (lo que ha sido mucho mejor para mí) por medio de frecuentes retiros, despojos,
y una profunda desolación, pobreza y carencia.
Esto lo repitió una y otra vez,
incluso después de grandes desbordamientos de Su amor en mi alma,
como un río que se desborda por todas sus orillas.
Pero, después de tales estaciones de regocijo,
si Él no hubiera velado Su presencia y vestido mi alma de luto,
yo podría (como el antiguo Israel), haber "`cantado Su alabanza,
pero pronto olvidado Sus obras.`"^
footnote:[Salmos 106: 12-13]
Más ahora,
a través de muchas tribulaciones y de los sabios movimientos de Su santa mano sobre mí,
mi alma se inclina,
y permanece sensible hasta el día de hoy de las tiernas impresiones de Su amor y bondad.
El sabor de la vida está todavía fresco dentro de mí. Él me ha guiado e instruido,
y (lo digo con reverencia) me ha mantenido y preservado.
Que todavía sea preservado,
y que de ahora en adelante Él me mantenga a salvo bajo Su omnipotente protección;
para andar como es digno de Él hasta el fin de mis días. Amén.

Durante una gran parte de los ejercicios mencionados, tuve frecuentes revelaciones,
y me fue concedido una medida de entendimiento vivo en relación
con la guerra espiritual y los misterios del reino de los cielos.
A menudo creía (habiéndolo visto en las revelaciones de la luz divina) que,
si permanecía fiel,
se me pediría que declarara a otros lo que el Señor
había hecho por mí y lo que me había mostrado,
e instara a mis semejantes a que buscaran una morada en
ese reino que no puede ser conmovido y que no se marchita.
Esta preocupación ahora comenzó a crecer sobre mí considerablemente,
incluso a tal grado que algunas veces sentía un impulso
vivo en las reuniones de comunicar algo a las personas.
Pero, temiendo comenzar en esta gran obra antes del tiempo oportuno, me contuve;
e incluso en varias ocasiones, cuando me encontraba listo para levantarme,
concluía que me mantendría en silencio una vez más.
Porque consideraba en mi interior que,
si mantenerme en silencio desagradaba al Señor, entonces Él me manifestaría Su desagrado;
pero que si me atrevía a decir una palabra en Su nombre sin Su santo requerimiento,
o demasiado rápido, entonces no sólo Lo disgustaría,
sino que también sería una carga para Su pueblo.
Y de esta manera,
podría tal vez entrar y enredarme en la práctica de hablar
a partir de influencias o impresiones demasiado pequeñas,
o confundir lamentablemente las chispas de mi propio fuego con las impresiones divinas;
lo que podría (si les daba lugar) hacer que esta confusión se incremente en mí,
causándome una gran pérdida en la vida verdadera y divina, si no mi perdición total.

En este cauteloso estado de mente pasé algún tiempo,
a menudo buscando al Señor por consejo y dirección en este y otros asuntos de importancia.
Y aunque creo que podría haber testificado públicamente en el nombre,
el poder y la aprobación del Señor, un poco antes de lo que lo hice,
puesto que mi renuencia provenía de la precaución y no de la obstinación,
rara vez sentí condenación por no hacerlo.
Sin embargo, en algunas ocasiones, sentí una verdadera inquietud por ese asunto.
Pero Aquel que me dio el impulso de predicar,
sabiendo muy bien la integridad de mi corazón,
y que me inclinaba fielmente a servirle sin adelantarme, ni quedarme detrás de mi Guía,
me trató con misericordia.
Él pasó por alto mis pequeñas resistencias,
me favoreció con nuevas y crecientes experiencias de Su amor,
y al final me mostró el camino de una manera tan clara y
contundente que borró toda duda y confusión de mi mente,
y pronuncié algunas palabras en nuestra reunión en Providence,
en el primer día de la semana, y el día diez del cuarto mes de 1774,
para mi satisfacción y creo que la de mis amigos también. Después
sentí la recompensa de la paz en mi pecho como un río de vida,
por un tiempo considerable, reconfortando dulcemente mi mente,
y confirmándome en esta solemne obra.
Las palabras que pronuncié fueron las siguientes: "`A menudo, sí, muy a menudo,
mi mente ha sido invadida con fervientes deseos de bien por las almas,
particularmente por los que asisten a esta reunión,
y de una manera especial por un remanente, cuyos corazones (considero yo) Dios ha tocado.
Y el lenguaje de mi mente a menudo ha sido de esta forma: Oh,
que Sion se levante y sacuda el polvo de la tierra, y se ponga sus hermosas vestiduras.`"
Habiendo pronunciado estas pocas palabras,
quebrantado de corazón y con gran cuidado de no sobrepasar los límites del orden divino,
pronuncié estas pocas palabras, me senté,
y fui (por así decirlo) sumergido en la presencia luminosa
de Aquel que habita en la eternidad y mora en la luz.

Después de un tiempo de regocijo celestial,
empecé a ser probado de nuevo con varios ejercicios y conflictos de la mente,
aunque aún era frecuentemente favorecido con el fluir del amor divino
de una manera muy reconfortante y satisfactoria para el alma.
En varias ocasiones tuve impresiones vivas para decir
unas pocas palabras en testimonio público,
pero aún esperaba en silencio hasta estar bien seguro.
El indecible consuelo que experimenté al pronunciar por primera vez unas
cuantas palabras (después de haberme abstenido durante un tiempo considerable,
en lugar de proceder apresuradamente) me confirmó
que hay una mayor seguridad en exprimir el vellón,
y probarlo tanto húmedo como seco,^
footnote:[Jueces 6:36-40]
que precipitarse en las primeras operaciones o revelaciones del Espíritu.
Mientras esperaba por más claridad, con temor de correr demasiado rápido,
fui favorecido con la experiencia del fuego del Señor
encendido de forma correcta sobre Su altar,
y con la evidencia de una ofrenda preparada por Él mismo.
Y estoy completamente convencido de que estas ofrendas (y solo estas),
son las ofrendas que encontrarán aceptación ante Él.

Tanto ahora como en la antigüedad, existe el fuego extraño;^
footnote:[Levítico 10:1-3]
y no tiene más lugar o aprobación ahora en la adoración del evangelio,
que lo que tuvo en las ofrendas bajo la ley,
donde encontramos que estaba estrictamente prohibido.
Y ya sea que ahora se conozca y se entienda o no,
la prohibición en contra de ello es tan obligatoria en todos los verdaderos
adoradores en nuestro día como lo fue en los tiempos antiguos.
¡Oh,
que Israel cumpla siempre esta importante prohibición! Estoy persuadido
de que su debida observancia contribuiría en gran medida al resplandor
y prosperidad de nuestra sociedad religiosa,
y a la propagación y progreso del reino del Mesías.

¡Ay de los profesantes cristianos de nuestro día! ¡Qué poco
conscientes están del predominio de la idolatría entre ellos!
Pero en su fuente, origen y sustancia,
es esa misma idolatría que es tan repetida y severamente reprobada en las Escrituras.
Porque en verdad,
cada ofrenda que no provenga directamente de Dios
es idolatría y no es más útil para los hombres,
o aceptable para Dios,
que la idolatría que era común entre los judíos. La apresurada voluntad
y precipitada pasión que el espíritu del hombre posee pueden,
en cualquier momento, impulsarle a pronunciar cualquier cosa que imagine.
Pero para pedir correctamente una petición a Dios, o hablar en Su nombre,
siempre se necesita Su asistencia divina, viva y directa.

"`El que creyere, no se apresure.`"^
footnote:[Isaías 28:16]
Verdaderamente, el que cree correctamente, no se atreve a apresurarse;
pues siempre sabe que su ayuda está solamente en Dios; que la raíz debe sostenerlo,
y no él a la raíz; que Dios debe moverlo, y que él no puede mover a Dios.
El que se precipita a la oración, a la predicación,
etc. antes de que Cristo (la vida) lo mueva de manera viva a ello, se apresura.
Pero el verdadero creyente, cree y espera la venida viva (en Espíritu) de Cristo,
Su vida; y así, Cristo es el que vive y actúa en él.

Mi segunda aparición pública en el ministerio fue en la casa de reuniones en Smithfield,
el diecinueve del décimo mes de 1774,
cuando me sentí impulsado a animar a los hermanos a mantener cuidadosamente
sus corazones vueltos al Señor cuando no están en nuestras reuniones;
y a exhortar a los Amigos a que se acerquen a Él día a día,
para que las fuerzas sean renovadas, y se conserve el sabor divino de la vida,
no sea que perdamos el sentido vivo de lo que a menudo misericordiosamente
disfrutamos durante nuestras reuniones.
La vida divina me acompañó en este pequeño testimonio, como en el anterior,
y después de la reunión disfruté de la dulce influencia
de Aquel que es el Dios de mi salvación,
de tal manera que fue de gran confirmación y aliento.

Después de esto, continué buscando y esperando en Dios para recibir consejo y dirección;
y manteniendo mi corazón en esta postura,
fui favorecido con una renovación e incremento de mi cercanía a Él,
y experimenté instrucciones frescas a mi mente.
Hablé públicamente de la verdad muy pocas veces,
y la mayoría de las veces con apenas unas pocas palabras a la vez.
Sin embargo, algunas veces sentí que había hablado demasiado,
por lo que sentía más dolor que el que alguna vez he sentido por mantenerme en silencio.
Pero, por la misericordiosa preservación de Dios,
rara vez (que yo recuerde) he hablado más a menudo o he dicho más de lo
que ha sido necesario para el cumplimiento de mi deber ante el Señor,
y (hasta donde sé) para el consuelo de mis hermanos.
¡Bendito sea el nombre del Señor mi Dios!
Me postro con reverencia ante Él,
por Su presencia que dirige y preserva a través de muchas pruebas profundas.
Él ha estado conmigo en las alturas y en las profundidades; ha entesado mi arco,
y cubierto mi cabeza en el día de batalla.
Que pueda servirle fielmente todos los días de mi estancia aquí,
hasta que me vaya y ya no sea visto por los hombres.

[.asterism]
'''

[.emphasized]
Job Scott era maestro de escuela de profesión,
pero se convirtió en un ministro dotado y muy amado en la Sociedad de los Amigos.
Era conocido por su total dependencia del movimiento
y del poder inmediato del Espíritu Santo,
y por no estar dispuesto a ministrar sin un sentido
claro de la voluntad del Señor. En ocasiones,
mientras predicaba, dejaba de hablar repentinamente y se sentaba, explicando luego que,
habiendo perdido el sentido de la autoridad y dirección del Espíritu de Dios,
no podía hacer nada sin él. En 1792,
se sintió guiado a realizar un viaje a Europa en la obra del evangelio,
y durante algunos meses viajó y predicó en Inglaterra e Irlanda,
tanto en las reuniones de los Amigos como en aquellas otras sociedades cristianas.
Hacia finales del año 1793, mientras ministraba en Ballitore, Irlanda,
y hospedándose en la casa de Elizabeth Shackleton, enfermó de viruela,
y después de una corta pero agonizante lucha contra la enfermedad,
terminó su carrera a los 42 años. Justo antes de su muerte, escribió en su diario:
"`Todos los conflictos pasados, por muy dolorosos que fueron en su tiempo,
ahora son más livianos que la vanidad,
salvo en la medida en que ahora veo que han contribuido
en gran manera a la santificación del alma.
Y ahora los recuerdo con temor y gratitud ante Aquel que
no ha dejado de preservarme a través de todos ellos.`"
